### ISSUE TITLE
Non Root

### ISSUE THREAD

**Issue by The-Repo-Club** [XDream8/revanced-creator#18]
hey mate can you add the non root apks to the releases too please pal?

**Comment by XDream8** [comment]
Hey mate, actually releases contains the **stock apps** and this script downloads these and create revanced apk's. this is because i could not find a way to download these apks with curl from apkmirror or apkpure since they both have protection. You can download nonroot apk's from [action artifacts](https://github.com/XDream8/revanced-creator/actions/workflows/Build.yml). select the latest and in the bottom of the page you will see the artifacts

**Comment by The-Repo-Club** [comment]
ok cheers mate that works :)
